#sudo: required
#
#language: ruby
#
#services:
#  - docker
#
#before_install:
#  - docker build -t carlad/sinatra .
#  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
#
#script:
#  - bundle exec rake test

sudo: required
language: go

env:
  # You may want to update this to whatever the latest version is, or keep it
  # the same as your local machines. However, I have only tested it with 1.8.0+.
  # There should be a time in the future when this is not necessary - it is
  # explained in more detail below.
  DOCKER_COMPOSE_VERSION: 1.8.0

services:
  - docker

before_install:

  - docker ps

  - docker-compose --version

  - sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

  - docker-compose --version

# safelist
branches:
  only:
  - travis