sudo: required
language: go

services:
  - docker

install:
  - ./gradlew release -Prelease.releaseVersion=`cat VERSION` -Prelease.newVersion=`cat VERSION`

script: docker-compose up prod-build-dns-proxy-server

after_success:

  - source ./builder upload-release

branches:
  only:
  - travis