sudo: required

services:
  - docker

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker-compose up --abort-on-container-exit prod-ci-deploy; fi
  - if [ "$TRAVIS_BRANCH" != "master" ] ; then docker-compose up --abort-on-container-exit prod-build-dns-proxy-server; fi

branches:
  only:
  - master
