#sudo: required
#
#language: ruby
#
#services:
#  - docker
#
#before_install:
#  - docker build -t carlad/sinatra .
#  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
#
#script:
#  - bundle exec rake test

sudo: required
language: go

services:
  - docker

install:

  - gradle release -Prelease.releaseVersion=2.1.2 -Prelease.newVersion=2.1.3

script: docker-compose build prod-build-docker-dns-proy-server

deploy:
  provider: releases
  api_key: $REPO_TOKEN
  file: build/dns-proxy-server-*.tgz
  skip_cleanup: true
  on:
    tags: true

# safelist
branches:
  only:
  - travis