sudo: required
language: go

services:
  - docker

install:
#  - source ./builder setup-repository
  - ./gradlew release -Prelease.releaseVersion=`cat VERSION` -Prelease.newVersion=`cat VERSION`

script: docker-compose up prod-build-dns-proxy-server

#after_success:
#
#  - source ./builder upload-release

branches:
  only:
  - travis

deploy:
  provider: releases
  api_key: $REPO_TOKEN
  file:
    - build/dns-proxy-server-*.tgz
  skip_cleanup: true
  on:
    repo: mageddo/dns-proxy-server
    branch: travis
    tags: false
