version: '2'
services:

  gocompiler-docker-dns-proxy: # base compiler
    image: golang:1.9
    container_name: gocompiler
    working_dir: /app/src/github.com/mageddo/dns-proxy-server
    volumes:
      - $PWD:/app/src/github.com/mageddo/dns-proxy-server
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    environment:
      - TERM=xterm
      - GOPATH=/app
      - MG_WORK_DIR=/app/src/github.com/mageddo/dns-proxy-server
    hostname: gocompiler.dev
    network_mode: bridge
  prod-docker-dns-prod-server: # run from a  docker image
    container_name: dns-proxy-server
    image: defreitas/dns-proxy-server:2.1.5
    hostname: dns.mageddo
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - 5380:5380
    network_mode: bridge
  prod-build-docker-dns-proy-server: # build the docker image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-dns-server-docker-compiler
    image: defreitas/dns-proxy-server:2.1.5
  prod-build-dns-proxy-server: # build the binary
    extends: gocompiler-docker-dns-proxy
    container_name: docker-dns-server-compiler
    command: bash -c "./builder build"
