version: '2'
services:
  prod-dns-proy-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-dns-server
    image: reg.mageddo.com:5000/mageddo/docker-dns-server:2.0.1
    hostname: dns.mageddo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5380:5380
    network_mode: bridge
  gocompiler:
    image: golang:1.7.4
    container_name: gocompiler
    volumes:
      - $PWD:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment: 
      - TERM=xterm
      - GOPATH=/app
    working_dir: /app
    hostname: gocompiler.dev
    ports:
      - 5380:5380
    network_mode: bridge
  prod-build-dns-proxy-server:
    extends: gocompiler
    container_name: docker-dns-server-compiler
    command: bash -c "mkdir -p build/ && cd src && go build -v -o ../build/docker-dns-server"