version: '2'
services:
  gocompiler:
    image: golang:1.7.4
    container_name: gocompiler
    volumes:
      - $PWD:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment: 
      - TERM=xterm
      - GOPATH=/app
    working_dir: /app
    hostname: gocompiler.dev
    network_mode: bridge